### ISSUE TITLE
cnu cnupro .sogang.ac.kr 이 텅 비었어요. 시험이 끝나면 fb.com/groups/SGCSCNU/ 등으로 리다이렉션해주세요. (냉무)

### ISSUE THREAD

**Issue by minhoryang** [CNU-Developers/CNU-ServerUtility#7]

**Comment by minhoryang** [comment]
cnupro:80은 외부에서 접속이 안되네요. cnu:80만 하셔도 되겠어요!

**Comment by taeguk** [comment]
cnupro (.200.109 ) 외부 접속 가능해졌습니다.

**Comment by taeguk** [comment]
cnu.sogang.ac.kr cnupro.sogang.ac.kr 둘 다 fb.com/groups/SGCSCNU/ 로 리다이렉션 해놧습니다.
